"""add seats

Revision ID: b6da4ed54b01
Revises: 190e91229d4f
Create Date: 2024-10-23 13:18:37.758892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6da4ed54b01'
down_revision: Union[str, None] = '190e91229d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('train_name', sa.String(), nullable=False),
    sa.Column('booking_reference', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['train_name'], ['trains.name'], ),
    sa.PrimaryKeyConstraint('id', 'number'),
    sa.UniqueConstraint('train_name', 'number', name='unique_constraint_train_name_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seats')
    # ### end Alembic commands ###
