#!/bin/bash

remote="$1"
url="$2"

zero=$(git hash-object --stdin </dev/null | tr '[0-9a-f]' '0')

while read local_ref local_oid remote_ref remote_oid
do
	if test "$local_oid" = "$zero"
	then
		echo "Deleting stuff, nothing to do"
	else
    set -x
    set -e
    deactivate || true
    poetry run flake8
    poetry run mypy
    poetry run pytest
  fi
done
